### ISSUE TITLE
Please Remove Credentials.pyc

### ISSUE THREAD

**Issue by manosteele117** [kevinkuo52/NDL_Disney_Chatbot#1]

**Comment by kevinkuo52** [comment]
@dundalkian can you help raise a PR

**Comment by dundalkian** [comment]
![6a6d1124cf69e5588588bc7e397598f6](https://github.com/kevinkuo52/NDL_Disney_Chatbot/assets/25651548/a709aaa2-9bad-4bac-942c-7ca06171eac3)

**Comment by kevinkuo52** [comment]
lgtm create a pr bro

**Comment by kevinkuo52** [comment]
done https://github.com/kevinkuo52/NDL_Disney_Chatbot/commit/aec5122f81fb79647a07049825ef2105bae90ed4

**Comment by kevinkuo52** [comment]
jk
removed now (not really) https://github.com/kevinkuo52/NDL_Disney_Chatbot/commit/bdf39fc92126921fbd96cac648945925a1182c0a

**Comment by manosteele117** [comment]
LGTM

**Comment by gharris1727** [comment]
I validated this fix.

+1 (binding)

Thanks,
Greg
